<script setup lang="ts">
defineProps<{
  html: string;
  name: string;
  downloadUrl: string;
}>();
</script>

<template>
  <div class="w-full flex flex-col gap-4">
    <div class="flex-split">
      <span class="text-sm text-fg-muted font-mono">{{ name }}</span>
      <a :href="downloadUrl" :download="name" class="btn">
        <span class="i-lucide:download w-3.5 h-3.5" aria-hidden="true" />
        download
      </a>
    </div>
    <!-- eslint-disable-next-line vue/no-v-html (html is server generated by markdown-it) -->
    <div
      v-html="html"
      class="prose prose-invert max-w-none rounded-xl border border-border bg-bg-subtle p-6"
    />
  </div>
</template>
